const mongoose = require('mongoose')

var PostMessage = mongoose.model('PostMessage',
{
    // title : {type:String},
    // message : {type:String},
    photograph	:	{type:String},
    firstname	:	{type:String},
    middlename	:	{type:String},
    lastname	:	{type:String},
    gender	:	{type:String},
    bday	:	{type:String},
    apt	:	{type:String},
    floor	:	{type:String},
    street	:	{type:String},
    city	:	{type:String},
    state	:	{type:String},
    country	:	{type:String},
    zip	:	{type:Number},
    tapt	:	{type:String},
    tfloor	:	{type:String},
    tstreet	:	{type:String},
    tcity	:	{type:String},
    tstate	:	{type:String},
    tcountry	:	{type:String},
    tzip	:	{type:Number},
    countrycode	:	{type:Number},
    areacode	:	{type:Number},
    phonenum	:	{type:Number},
    mcountrycode	:	{type:Number},
    mareacode	:	{type:Number},
    mmobilenum	:	{type:Number},
    ecountrycode	:	{type:Number},
    eareacode	:	{type:Number},
    emobilenum	:	{type:Number},
    marriage	:	{type:String},
    email1	:	{type:String},
    emailAlt	:	{type:String},
    passport	:	{type:String},
    visa	:	{type:String},
    visaexpdate	:	{type:String},
    insexpdate	:	{type:String},
    cv	:	{type:String},
    dfj	:	{type:String},
    basicSal	:	{type:Number},
    otherAll	:	{type:Number},
    incentives	:	{type:Number},
    worklocation	:	{type:String},
    department	:	{type:String},
    joininggrade	:	{type:String},
    role	:	{type:String},
    contract	:	{type:String},
    acname	:	{type:String},
    bank	:	{type:String},
    branchcode	:	{type:String},
    ifsc	:	{type:String},
    swiftcode	:	{type:String},
    acnum	:	{type:Number},
    ibannum	:	{type:Number}   

},'emp') //colllection Name

module.exports = { PostMessage}